### ISSUE TITLE
Lista de Pokemons

### ISSUE THREAD

**Issue by lfsmariz** [mustang-roy/pokedex#10]
O usuário deve poder interagir através de uma listagem na lateral direita conforme layout.

 - [x] barra lateral com scroll.
 - [x] nº - nomePokemon.
 - [x] Clique no pokemon deve trazer suas informações.

**Comment by herculesgabriel** [comment]
@danwhat,  é realmente necessário mostrar o número do pokémon na lista de pokémons, ainda mais naquele formato? Levando em consideração o tamanho atual da caixa resta pouco espaço para o nome do pokémon.

**Comment by danwhat** [comment]
![images](https://user-images.githubusercontent.com/62217873/96997650-8b8b0e80-1508-11eb-9027-7af9a6f8c4c7.png)
![images (11)](https://user-images.githubusercontent.com/62217873/96997651-8c23a500-1508-11eb-9152-f8483e18a271.jpeg)

É necessário sim Hercules. A numeração antes do nome é a fonte 8 bits é marca registrada de todo jogo de pokemon portátil. Podemos procurar uma fonte que ocupe menos espaço ou diminuir seu tamanho para resolver o problema.

**Comment by herculesgabriel** [comment]
@danwhat , beleza! Por ora eu vou diminuir a fonte e/ou aumentar o tamanho da linha.

**Comment by herculesgabriel** [comment]
O cara que criou o requisito "ordenar alfabeticamente" não faz ideia do que tá fazendo na vida.
