### ISSUE TITLE
Criar projeto no figma

### ISSUE THREAD

**Issue by lfsmariz** [mustang-roy/pokedex#6]
Criação do template no figma para base do front-end do projeto

relaciona a US #4

**Comment by danwhat** [comment]
Primeiramente digdin:
https://www.figma.com/file/kZeQKu8q9M4nTrRgQnNiMu/Untitled?node-id=0%3A1

**Comment by herculesgabriel** [comment]
É preciso converter as unidades de peso e alturas do pokemons para o sistema internacional.
